export type Role = 'system' | 'user' | 'assistant' | 'tool';

/**
 * A single non-text (or non-plain-text) piece of a message's content, e.g. a
 * tool call, tool result, or image. `type` selects which `contentCounters`
 * entry is used to count its tokens.
 */
export interface ContentBlock {
  type: string;
  text?: string;
  [key: string]: unknown;
}

export interface BudgetMessage {
  /** Stable, unique identifier. Auto-generated by `addMessage` if omitted. */
  id: string;
  role: Role;
  content: string | ContentBlock[];
  /** Optional display/participant name, counted as overhead by some providers. */
  name?: string;
  /** Never evicted or summarized by any built-in strategy. */
  pinned?: boolean;
  /** Higher = more important. Used by the `priority` strategy. Default 0. */
  priority?: number;
  /**
   * Links a tool-result message back to the message that produced the tool
   * call it answers (that message's `id`). Any two messages sharing a
   * call/result relationship via this field are treated as one atomic unit
   * by every built-in strategy: both are kept, or both are evicted.
   */
  toolCallId?: string;
  /** Arbitrary caller metadata. Built-in synthetic summaries use this. */
  metadata?: Record<string, unknown>;
  /** Unix ms timestamp, set automatically by `addMessage` if omitted. */
  timestamp?: number;
  /** Cached token count for this message, including overhead. Read-only. */
  tokens?: number;
}

/** Script profile for the built-in heuristic estimator (FR2-7.1). */
export type EstimatorProfile = 'latin' | 'cjk' | 'cyrillic' | 'auto-detect';

export interface Tokenizer {
  count(text: string): number;
  encode?(text: string): number[];
}

export type ContentCounter = (block: ContentBlock) => number;

export interface StrategyContext {
  /** maxTokens - reserve. The number strategies must respect. */
  effectiveBudget: number;
  /** Token total of the messages array passed into `apply`. */
  tokensUsed: number;
  /** Counts a full message list, including per-message overhead. */
  countTokens: (messages: BudgetMessage[]) => number;
  /** Counts a single message, including its overhead. */
  countMessage: (message: BudgetMessage) => number;
  /**
   * Wraps a summary string as a synthetic pinned-safe replacement message.
   * Strategies that synthesize replacement content (e.g. summarize-oldest)
   * should use this so downstream eviction accounting stays consistent.
   * `extraMetadata` is merged into the synthetic message's `metadata`
   * (e.g. `{ summaryDepth }` for recursive summarization, FR2-5.2).
   */
  makeSynthetic: (content: string, sourceIds: string[], extraMetadata?: Record<string, unknown>) => BudgetMessage;
  /**
   * Optional trace sink (Phase 2 §3.4). When present, a strategy that
   * evicts or summarizes anything should call this once with a summary of
   * what it did and why, so `budget.explain()`/the `decision` event can
   * report it. Absent when nobody is listening — cheap to skip.
   */
  trace?: (step: StrategyStepTrace) => void;
}

export interface Strategy {
  name: string;
  /**
   * True if `apply` is guaranteed to return synchronously for this
   * strategy instance (never a Promise). `getContextSync` requires this.
   */
  sync: boolean;
  apply(messages: BudgetMessage[], ctx: StrategyContext): Promise<BudgetMessage[]> | BudgetMessage[];
}

export interface EvictedInfo {
  strategyApplied: string;
  /** Original (pre-strategy) messages that are absent from the strategized output. */
  messages: BudgetMessage[];
  /** Synthetic replacement messages introduced by the strategy, if any. */
  replacedBy: BudgetMessage[];
}

export interface OverflowInfo {
  reason: 'single-message-exceeds-budget' | 'unresolvable-after-strategy';
  message?: BudgetMessage;
  tokensUsed: number;
  effectiveBudget: number;
}

export interface WarningInfo extends Stats {
  threshold: number;
}

export interface StrategyErrorInfo {
  strategyName: string;
  error: unknown;
  recovered: boolean;
}

/** An in-progress streamed message's running, approximate token count (Phase 2 §3.3). */
export interface StreamingEstimate {
  id: string;
  estimatedTokens: number;
}

export interface Stats {
  tokensUsed: number;
  tokensRemaining: number;
  maxTokens: number;
  reserve: number;
  messageCount: number;
  pinnedCount: number;
  /** Open streams' running token estimates, included in `tokensUsed` (FR2-3.5). */
  streaming: StreamingEstimate[];
  /** Cumulative cost so far, only present when `costModel` is configured (Phase 3). */
  cost?: CostBreakdown;
}

export interface ContextResult {
  messages: BudgetMessage[];
  tokensUsed: number;
  tokensRemaining: number;
  evicted: BudgetMessage[];
  strategyApplied: string;
}

/** One message a strategy step evicted or folded into a synthetic summary, with a human-readable reason. */
export interface TraceDecision {
  id: string;
  reason: string;
}

/**
 * One strategy's contribution to a `getContext()`/`getContextSync()` call.
 * A plain strategy produces exactly one; a `chain([...])` produces one per
 * member, in the order they ran (FR2-4.3).
 */
export interface StrategyStepTrace {
  strategyName: string;
  tokensBefore: number;
  tokensAfter: number;
  messagesConsidered: number;
  evicted: TraceDecision[];
  /** Synthetic summary messages this step introduced, if any (summarize-oldest). */
  synthesized: Array<{ id: string; sourceIds: string[]; reason: string }>;
}

/**
 * Structured trace of the most recent `getContext()`/`getContextSync()`
 * call (FR2-4.1). JSON-serializable: no circular refs, no functions.
 */
export interface ExplainReport {
  steps: StrategyStepTrace[];
  tokensBefore: number;
  tokensAfter: number;
  tokensRemaining: number;
  strategyApplied: string;
  timestamp: number;
}

export interface TokenBudgetEvents {
  warning: (info: WarningInfo) => void;
  overflow: (info: OverflowInfo) => void;
  evicted: (info: EvictedInfo) => void;
  'strategy-error': (info: StrategyErrorInfo) => void;
  /** Fired every time a strategy runs, mirroring `explain()`'s output (FR2-4.4). */
  decision: (report: ExplainReport) => void;
  /** Fired once when cumulative cost first crosses `costWarningThreshold` (Phase 3). */
  costWarning: (info: CostWarningInfo) => void;
  /**
   * Fired with the current lifetime usage report after every
   * `getContext()`/`getContextSync()` call, throttled by
   * `usageSnapshotIntervalMs` (Phase 3). `onUsageSnapshot` in the config is
   * sugar for subscribing to this event at construction time — subscribe
   * with `on('usageSnapshot', ...)` directly to attach/detach a listener
   * after construction (e.g. from an instrumentation package).
   */
  usageSnapshot: (report: UsageReport, timestamp: number) => void;
}

export type TokenBudgetEventName = keyof TokenBudgetEvents;

/** Shape accepted by `addMessage`/`estimateBeforeAdd`: everything but the derived fields. */
export type AddMessageInput = Omit<BudgetMessage, 'id' | 'tokens' | 'timestamp'> &
  Partial<Pick<BudgetMessage, 'id' | 'timestamp'>>;

/** A serialized open stream (Phase 2 §3.6), only present when `serialize({ includeOpenStreams: true })` was used. */
export interface SerializedStream {
  id: string;
  role: Role;
  parts: Array<string | ContentBlock>;
  metadata?: Record<string, unknown>;
  /** Always true — signals the caller that this content was mid-flight when serialized, not a finished message. */
  wasInterrupted: true;
}

/**
 * Plain, JSON-serializable snapshot of a `TokenBudget`'s state (FR2-6.1).
 * Excludes anything that can't be serialized generically — the tokenizer
 * instance, strategy, `messageOverhead`/`contentCounters` functions — the
 * caller re-supplies those via `deserialize()`'s `overrides`.
 */
export interface SerializedState {
  /** Schema version of this snapshot, for forward/backward-compatible migration (FR2-6.5). */
  schemaVersion: number;
  maxTokens: number;
  reserve: number;
  warningThreshold: number;
  charsPerToken: number;
  devMode: boolean;
  onStrategyDuringStream: 'skip' | 'error';
  messages: BudgetMessage[];
  /** Open streams, only present when serialized with `includeOpenStreams: true` (FR2-6.4). */
  streaming?: SerializedStream[];
}

export interface TokenBudgetConfig {
  /**
   * Total context window size, in tokens. Optional if `model` is set to a
   * name listed in `MODEL_CONTEXT_WINDOWS` — its known context-window size
   * is used instead. Required (and throws if missing) when `model` is
   * unset or unrecognized: an unknown budget is never silently guessed.
   */
  maxTokens?: number;
  /** Tokens reserved for the model's expected output. Default 0. */
  reserve?: number;
  /** A Tokenizer instance, or the string 'estimate' for the built-in heuristic. Default 'estimate'. */
  tokenizer?: Tokenizer | 'estimate';
  /** Heuristic estimator tuning: characters per token. Takes precedence over `estimatorProfile` when set. */
  charsPerToken?: number;
  /**
   * Heuristic estimator script profile (FR2-7.1). Default `'latin'`
   * (ratio 4 — Phase 1's exact original behavior). Ignored if
   * `charsPerToken` is also set.
   */
  estimatorProfile?: EstimatorProfile;
  /** Fraction of the effective budget at which a `warning` event fires. Default 0.8. */
  warningThreshold?: number;
  /** Eviction/compression strategy applied by `getContext`/`getContextSync`. Default `dropOldest()`. */
  strategy?: Strategy;
  /** Per-message fixed overhead (role/formatting tokens), added on top of content tokens. */
  messageOverhead?: (message: BudgetMessage) => number;
  /** Per-content-block-type token counters, keyed by `ContentBlock.type`. */
  contentCounters?: Record<string, ContentCounter>;
  /**
   * When true, `console.debug`-logs every `ExplainReport` as it's produced
   * (FR2-4.5). Default false — never logs unless explicitly opted in.
   */
  devMode?: boolean;
  /**
   * What `getContext()`/`getContextSync()` do while a stream is open
   * (FR2-3.7). Open-stream content is never visible to strategies either
   * way (it isn't part of the buffer until `endStream`/`abortStream`).
   * 'skip' (default) proceeds normally, ignoring the open stream. 'error'
   * throws, refusing to build a context that doesn't reflect in-flight
   * content.
   */
  onStrategyDuringStream?: 'skip' | 'error';
  /**
   * Called (debounced by `persistDebounceMs`) with the current
   * `serialize()`-shaped state after every buffer mutation, so an
   * application can auto-persist without calling `serialize()` itself
   * (FR2-6.3). No storage backend is bundled — write `state` wherever you
   * like (Redis, SQLite, IndexedDB, ...).
   */
  onPersist?: (state: SerializedState) => void | Promise<void>;
  /**
   * Debounce window (ms) for `onPersist`, trailing-edge: rapid mutations
   * coalesce into one call carrying the latest state once the window
   * elapses — never dropped, just delayed (NFR2-7). Default 0: call
   * `onPersist` synchronously after every mutation.
   */
  persistDebounceMs?: number;
  /** Pluggable cost model for cost accounting (Phase 3). Ignored unless `model` is also set. */
  costModel?: CostModel;
  /**
   * The model name passed to `costModel.costPerToken()` for cost accounting,
   * and, when `maxTokens` is omitted, looked up in `MODEL_CONTEXT_WINDOWS`
   * to auto-derive it. Serves both independently — set it for either or both.
   */
  model?: string;
  /** Cumulative cost threshold that fires the `costWarning` event once. */
  costWarningThreshold?: number;
  /**
   * Cumulative cost ceiling. Once reached, `maxCostPolicy` decides what
   * happens to the *next* `addMessage()` call — the message that pushed
   * cost to the ceiling is always recorded, only later ones are affected.
   */
  maxCost?: number;
  /**
   * Policy applied once `maxCost` is reached. `'block-new-messages'`
   * throws from `addMessage()` *before* any state changes, so a rejected
   * message leaves usage/cost accounting untouched. A callback instead
   * receives `{ cumulativeCost, threshold, currency }` on every
   * over-ceiling `addMessage()` call and does not block it. No default —
   * omitting this makes `maxCost` a no-op.
   */
  maxCostPolicy?: CostCeilingPolicy;
  /**
   * Sugar for `budget.on('usageSnapshot', fn)` at construction time — see
   * that event for details. Attach/detach after construction with
   * `on()`/`off()` directly instead (e.g. from an instrumentation package
   * wrapping an already-constructed budget).
   */
  onUsageSnapshot?: (report: UsageReport, timestamp: number) => void;
  /**
   * Minimum interval (ms) between `usageSnapshot` emissions. Default
   * 0/undefined: emit on every `getContext()`/`getContextSync()` call.
   */
  usageSnapshotIntervalMs?: number;
  /** Arbitrary tags carried on `UsageReport`/`AuditEvent` (e.g. `{ tenantId, userId }`). */
  tags?: Record<string, string>;
  /**
   * Pre-processor hook applied to every message before it's counted or
   * buffered (Phase 3) — e.g. to strip PII prior to token accounting and
   * storage. Runs once per `addMessage()` call, not on `editMessage()`.
   */
  redactor?: (message: BudgetMessage) => BudgetMessage;
  /** When true, calls `onAuditEvent` after every `getContext()`/`getContextSync()` call. Default false. */
  auditLog?: boolean;
  /**
   * Receives one `AuditEvent` per strategy decision when `auditLog` is
   * true — a structured, reproducible record of what ran and what it
   * evicted, for compliance logging. These events are plain, unsigned
   * data (no built-in tamper-evidence/hashing) — hash or sign them
   * yourself in the hook if your compliance requirements need that.
   */
  onAuditEvent?: (event: AuditEvent) => void | Promise<void>;
}

/** One strategy decision's audit record, emitted via `onAuditEvent` when `auditLog` is true (Phase 3). */
export interface AuditEvent {
  timestamp: number;
  strategyApplied: string;
  tokensBefore: number;
  tokensAfter: number;
  effectiveBudget: number;
  messagesConsidered: number;
  evictedIds: string[];
  synthesizedIds: string[];
  tags?: Record<string, string>;
}

/** Context passed to a `Scorer` for the `semanticRelevance` strategy (Phase 3). */
export interface ScoringContext {
  /** The full message buffer being scored. */
  buffer: BudgetMessage[];
  /** The message treated as the current query — the most recent `user` message, or the last message if none. */
  query: BudgetMessage;
  auxiliaryContext?: unknown;
}

/**
 * Pluggable relevance scorer for the `semanticRelevance` strategy. Higher
 * scores are more relevant and more likely to be retained. Bring your own
 * embedding/similarity implementation — see `token-budget-embeddings` for
 * a reference cosine-similarity implementation.
 */
export interface Scorer {
  score(message: BudgetMessage, context: ScoringContext): Promise<number> | number;
}

export interface CostBreakdown {
  inputCost: number;
  outputCost: number;
  totalCost: number;
  currency: string;
}

/** Pluggable per-token pricing for cost accounting (Phase 3). See `token-budget-pricing` for a static lookup table. */
export interface CostModel {
  costPerToken(role: Role, model: string, direction: 'input' | 'output'): number;
}

/**
 * Cumulative, lifetime usage/cost ledger (Phase 3) — unlike `stats()`,
 * which reflects the *current* buffer, every field here only ever grows:
 * `removeMessage`/`editMessage`/eviction don't retroactively adjust it,
 * the same way `totalMessagesProcessed` counts every message ever added,
 * including ones later evicted.
 */
export interface UsageReport {
  totalMessagesProcessed: number;
  totalTokensConsumed: Record<Role, number>;
  /** Messages evicted or folded into a summary, keyed by strategy name. */
  totalEvictions: Record<string, number>;
  /** Only present when `costModel` is configured. */
  totalCost?: CostBreakdown;
  tags?: Record<string, string>;
}

export interface CostWarningInfo {
  cumulativeCost: number;
  threshold: number;
  currency: string;
}

export type CostCeilingPolicyCallback = (info: CostWarningInfo) => void;

export type CostCeilingPolicy = 'block-new-messages' | CostCeilingPolicyCallback;
