export type Role = 'system' | 'user' | 'assistant' | 'tool';

/**
 * A single non-text (or non-plain-text) piece of a message's content, e.g. a
 * tool call, tool result, or image. `type` selects which `contentCounters`
 * entry is used to count its tokens.
 */
export interface ContentBlock {
  type: string;
  text?: string;
  [key: string]: unknown;
}

export interface BudgetMessage {
  /** Stable, unique identifier. Auto-generated by `addMessage` if omitted. */
  id: string;
  role: Role;
  content: string | ContentBlock[];
  /** Optional display/participant name, counted as overhead by some providers. */
  name?: string;
  /** Never evicted or summarized by any built-in strategy. */
  pinned?: boolean;
  /** Higher = more important. Used by the `priority` strategy. Default 0. */
  priority?: number;
  /**
   * Links a tool-result message back to the message that produced the tool
   * call it answers (that message's `id`). Any two messages sharing a
   * call/result relationship via this field are treated as one atomic unit
   * by every built-in strategy: both are kept, or both are evicted.
   */
  toolCallId?: string;
  /** Arbitrary caller metadata. Built-in synthetic summaries use this. */
  metadata?: Record<string, unknown>;
  /** Unix ms timestamp, set automatically by `addMessage` if omitted. */
  timestamp?: number;
  /** Cached token count for this message, including overhead. Read-only. */
  tokens?: number;
}

export interface Tokenizer {
  count(text: string): number;
  encode?(text: string): number[];
}

export type ContentCounter = (block: ContentBlock) => number;

export interface StrategyContext {
  /** maxTokens - reserve. The number strategies must respect. */
  effectiveBudget: number;
  /** Token total of the messages array passed into `apply`. */
  tokensUsed: number;
  /** Counts a full message list, including per-message overhead. */
  countTokens: (messages: BudgetMessage[]) => number;
  /** Counts a single message, including its overhead. */
  countMessage: (message: BudgetMessage) => number;
  /**
   * Wraps a summary string as a synthetic pinned-safe replacement message.
   * Strategies that synthesize replacement content (e.g. summarize-oldest)
   * should use this so downstream eviction accounting stays consistent.
   */
  makeSynthetic: (content: string, sourceIds: string[]) => BudgetMessage;
}

export interface Strategy {
  name: string;
  /**
   * True if `apply` is guaranteed to return synchronously for this
   * strategy instance (never a Promise). `getContextSync` requires this.
   */
  sync: boolean;
  apply(messages: BudgetMessage[], ctx: StrategyContext): Promise<BudgetMessage[]> | BudgetMessage[];
}

export interface EvictedInfo {
  strategyApplied: string;
  /** Original (pre-strategy) messages that are absent from the strategized output. */
  messages: BudgetMessage[];
  /** Synthetic replacement messages introduced by the strategy, if any. */
  replacedBy: BudgetMessage[];
}

export interface OverflowInfo {
  reason: 'single-message-exceeds-budget' | 'unresolvable-after-strategy';
  message?: BudgetMessage;
  tokensUsed: number;
  effectiveBudget: number;
}

export interface WarningInfo extends Stats {
  threshold: number;
}

export interface StrategyErrorInfo {
  strategyName: string;
  error: unknown;
  recovered: boolean;
}

export interface Stats {
  tokensUsed: number;
  tokensRemaining: number;
  maxTokens: number;
  reserve: number;
  messageCount: number;
  pinnedCount: number;
}

export interface ContextResult {
  messages: BudgetMessage[];
  tokensUsed: number;
  tokensRemaining: number;
  evicted: BudgetMessage[];
  strategyApplied: string;
}

export interface TokenBudgetEvents {
  warning: (info: WarningInfo) => void;
  overflow: (info: OverflowInfo) => void;
  evicted: (info: EvictedInfo) => void;
  'strategy-error': (info: StrategyErrorInfo) => void;
}

export type TokenBudgetEventName = keyof TokenBudgetEvents;

/** Shape accepted by `addMessage`/`estimateBeforeAdd`: everything but the derived fields. */
export type AddMessageInput = Omit<BudgetMessage, 'id' | 'tokens' | 'timestamp'> &
  Partial<Pick<BudgetMessage, 'id' | 'timestamp'>>;

export interface TokenBudgetConfig {
  /** Total context window size, in tokens. */
  maxTokens: number;
  /** Tokens reserved for the model's expected output. Default 0. */
  reserve?: number;
  /** A Tokenizer instance, or the string 'estimate' for the built-in heuristic. Default 'estimate'. */
  tokenizer?: Tokenizer | 'estimate';
  /** Heuristic estimator tuning: characters per token. Default 4. */
  charsPerToken?: number;
  /** Fraction of the effective budget at which a `warning` event fires. Default 0.8. */
  warningThreshold?: number;
  /** Eviction/compression strategy applied by `getContext`/`getContextSync`. Default `dropOldest()`. */
  strategy?: Strategy;
  /** Per-message fixed overhead (role/formatting tokens), added on top of content tokens. */
  messageOverhead?: (message: BudgetMessage) => number;
  /** Per-content-block-type token counters, keyed by `ContentBlock.type`. */
  contentCounters?: Record<string, ContentCounter>;
}
